# syntax=docker/dockerfile:1
# ──────────────────────────────────────────────────────────────────────────
# baref00t partner-portal — production multi-stage Dockerfile.
# Image: ghcr.io/becloudsmart-com/baref00t-portal:<tag>
#
# Build (from repo root, monorepo context):
#   docker build -f apps/partner-portal/Dockerfile -t baref00t-portal:dev .
#
# Build (from public mirror, single-package context — what partners use):
#   docker build -t baref00t-portal:dev .
#
# Both work because the COPY ordering only relies on files that exist in
# either context.
# ──────────────────────────────────────────────────────────────────────────

ARG NODE_VERSION=20-bookworm-slim

# ── Stage 1: install + build ───────────────────────────────────────────────
FROM node:${NODE_VERSION} AS build

ENV PNPM_HOME=/usr/local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH
ENV CI=1

RUN corepack enable && corepack prepare pnpm@9.12.3 --activate

WORKDIR /build

# Copy lockfiles + manifests first to maximise layer cache.
# tsconfig.base.json is required because apps/partner-portal/tsconfig.json
# extends "../../tsconfig.base.json"; without it tsc fails inside the
# container with "extends doesn't resolve correctly".
COPY pnpm-workspace.yaml* package.json pnpm-lock.yaml tsconfig.base.json* ./
COPY apps/partner-portal/package.json apps/partner-portal/package.json

# Install (workspace-aware in monorepo context; standalone in mirror context).
# `--filter` is a no-op outside a workspace, so the same line works in both.
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile --filter @baref00t/partner-portal...

# Copy the rest of the portal source.
COPY apps/partner-portal apps/partner-portal

# Build the Next.js standalone bundle.
RUN pnpm --filter @baref00t/partner-portal run build

# ── Stage 2: production runtime ────────────────────────────────────────────
FROM node:${NODE_VERSION} AS runtime

ENV NODE_ENV=production
ENV PORT=3000
WORKDIR /app

# Non-root user for the runtime container.
RUN groupadd --system --gid 1001 portal \
 && useradd --system --uid 1001 --gid portal portal

# Next.js standalone output bundles its own minimal node_modules in
# .next/standalone — copy that, plus static assets and public/.
COPY --from=build --chown=portal:portal /build/apps/partner-portal/.next/standalone ./
COPY --from=build --chown=portal:portal /build/apps/partner-portal/.next/static ./apps/partner-portal/.next/static
COPY --from=build --chown=portal:portal /build/apps/partner-portal/public ./apps/partner-portal/public

USER portal
EXPOSE 3000

# server.js is generated by Next when `output: 'standalone'`.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD node -e "fetch('http://localhost:'+(process.env.PORT||3000)+'/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

CMD ["node", "apps/partner-portal/server.js"]
